### ISSUE TITLE
Firebug 2.0 = no FirePHP menu

### ISSUE THREAD

**Issue by skunkbad** [firephp/firephp-extension#21]
FirePHP works (Thank God!), but the menu to turn it off and on is no longer available. This is with Firefox 30 and Firebug 2.0

**Comment by Nuc1eoN** [comment]
Same issue here. There is no icon.

**Comment by cadorn** [comment]
A new FirePHP extension has been released that works for Firefox >= 56.0.2.

See: http://firephp.org/
