### ISSUE TITLE
dead as off FF48

### ISSUE THREAD

**Issue by bkdotcom** [firephp/firephp-extension#27]
FF48 requires add-ons to be signed

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by cadorn** [comment]
It works for me when installing via: https://addons.mozilla.org/en-US/firefox/addon/firephp/

I'll have to investigate how I can sign unlisted addons.

**Comment by cadorn** [comment]
A new FirePHP extension has been released that works for Firefox >= 56.0.2.

See: http://firephp.org/
