### ISSUE TITLE
Further developement … dev setup for easier user contrib …

### ISSUE THREAD

**Issue by jdlx** [firephp/firephp-extension#29]
Dear Christoph,

firephp is somewhat aged by now and could use some love … while i could help on both PHP and JS i'm utterly clueless how to setup a FF extension coding dev environment. I tried to google it, but all i could find seemed pretty messy/complicated/outdated …

So maybe if you could line out - _in the wiki ?_ - how to set up a dev environment, there'd be a way better chance for firephp users – _as such most likely devs in some way_ – to step in and add improvements …

cheers,
Jan

**Comment by lorenzos** [comment]
See my comment here https://github.com/firephp/firephp-extension/issues/28#issuecomment-284151896
